async function handleInstallation(context) {
  const { installation, repositories } = context.payload;
  
  console.log(`Installation created for ${installation.account.login}`);
  console.log(`Repositories that can access the app: ${repositories.length}`);
  
  // Welcome the user with setup instructions
  try {
    await context.octokit.rest.issues.createComment({
      owner: installation.account.login,
      repo: repositories[0].name, // Comment on the first repo as a welcome
      issue_number: 1, // This might not exist, but we can try
      body: getWelcomeComment(installation, repositories),
    });
  } catch (error) {
    console.log('Could not post welcome comment, might be on a repo without issue #1');
  }
  
  // Store installation data in a database (in production)
  // For now, just log it
  console.log('Installation data:', {
    installationId: installation.id,
    account: installation.account,
    repositories: repositories.map(r => r.full_name),
    createdAt: new Date().toISOString(),
  });
}

function getWelcomeComment(installation, repositories) {
  const repoList = repositories.slice(0, 5).map(r => `• ${r.full_name}`).join('\n');
  const moreRepos = repositories.length > 5 ? `\n... and ${repositories.length - 5} more repositories` : '';
  
  return `🎉 Welcome to the **SolFoundry AI Code Review GitHub App**!

Thank you for installing the AI-powered code review bot on your repository. Here's what you need to know:

## ✅ What's Working
- **Multi-LLM Code Reviews**: Your PRs will be reviewed by Claude, OpenAI GPT-4, and Google Gemini
- **Security Analysis**: Automatic detection of security vulnerabilities
- **Performance Insights**: Performance optimization suggestions
- **Best Practices**: Code quality and maintainability feedback

## 🚀 How It Works
The app will automatically review every new pull request in your repository with:
- **AI-Powered Comments**: Constructive feedback from multiple AI models
- **Configurable Review Strictness**: Adjustable review intensity
- **File Type Filtering**: Focuses on relevant code files
- **Real-time Analysis**: Instant feedback as soon as PRs are created

## 🔧 Configuration Options
You can customize the AI review behavior by creating a `.github/ai-review-config.json` file in your repository:

\`\`\`json
{
  "strictness": "medium",
  "includeSecurity": true,
  "includePerformance": true,
  "includeBestPractices": true,
  "models": {
    "claude": { "enabled": true, "maxTokens": 4000 },
    "openai": { "enabled": true, "maxTokens": 4000 },
    "gemini": { "enabled": true, "maxTokens": 4000 }
  },
  "excludePatterns": [
    "**/*.md",
    "**/*.txt",
    "**/node_modules/**"
  ],
  "fileTypes": {
    "include": ["**/*.js", "**/*.ts", "**/*.jsx", "**/*.tsx", "**/*.py"]
  }
}
\`\`\`

## 📋 Installed Repositories
${repoList}${moreRepos}

## 🛠️ Need Help?
If you need assistance with configuration or have questions about the reviews, feel free to:
- Check our [documentation](https://github.com/SolFoundry/solfoundry)
- Open an issue in this repository
- Contact the SolFoundry team

---

*This welcome message was automatically generated by the SolFoundry AI Code Review GitHub App.*`;
}

module.exports = { handleInstallation };